<a href="https://colab.research.google.com/github/ziaArzoo/spark-foundation/blob/main/analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


EXPLORATORY DATA ANALYSIS

By :** MD ZIA ARZOO  **                                                                        
*data science and business analytics intern @The spark foundation*

*#GRIPAUGUST21 #TSF #DATASCIENCE*

In [ ]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
from google.colab import files
uploaded = files.upload()

Saving SampleSuperstore (1).csv to SampleSuperstore (1) (1).csv


In [12]:
df=pd.read_csv("SampleSuperstore(1).csv")
df.head()

FileNotFoundError: ignored

In [ ]:
df.info()
df.isnull().sum()

In [ ]:
df.shape


In [ ]:
sns.set_style('darkgrid')
sns.scatterplot(y= data['Scores'], x= data['Hours'])
plt.title('Marks Vs Study Hours',size=20)
plt.ylabel('Marks Percentage', size=12)
plt.xlabel('Hours Studied', size=12)
plt.show()

NameError: ignored

In [ ]:
plt.figure(figsize=(8,5))
sns.kdeplot(df['Sales'],color='red',label='Sales',shade=True,bw=25)
sns.kdeplot(df['Profit'],color='Blue',label='Profit',shade=True,bw=25)
plt.xlim([-100,1000])
plt.legend()

SyntaxError: ignored

In [ ]:
sns.pairplot(df,hue='Category')


array([1])

In [ ]:
sns.pairplot(df,hue='Region')


In [ ]:
sns.pairplot(df,hue='Segment')


array([3.14, 3.14, 3.14, 3.14])

In [ ]:
df.corr()


array([3.14, 3.14, 3.14, 3.14, 3.14])

In [ ]:
sns.heatmap(df.corr(),cmap='rocket_r',annot=True)


array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [ ]:
plt.figure(figsize=(20,8))
sns.countplot(df['Sub-Category'])
plt.title('Sub-Category',fontsize=20)